language: d
d:
    - dmd
    - ldc

jobs:
    include:
        - stage: deploy
          d: ldc
          script: echo "Minify clientside & build release version (ldc) & deploy to digitalocean (TODO)"
          if: branch = live AND type = push
